const useStateQuestions = [
    { id: 1, level: "Basics", question: "What is useState and why do we use it in React?" },
    { id: 2, level: "Basics", question: "Can we update the state directly in React? Why or why not?" },
    { id: 3, level: "Basics", question: "What is the difference between direct mutation of state and updating state using setState?" },
    { id: 4, level: "Basics", question: "How does React handle useState updates? Are they synchronous or asynchronous?" },
    { id: 5, level: "Basics", question: "What happens when you call the state setter function in useState multiple times in one render cycle?" },
    { id: 6, level: "Basics", question: "Can we use useState multiple times in a single component? Why or why not?" },
    { id: 7, level: "Basics", question: "What happens if you pass a function to useState as its initial value? (lazy initialization)" },
    { id: 8, level: "Basics", question: "How does React decide when to re-render a component when using useState?" },
    { id: 9, level: "Basics", question: "Why doesn’t updating state immediately reflect the new value after calling the setter?" },
    { id: 10, level: "Basics", question: "How do you update state based on the previous value in useState?" },
    { id: 11, level: "Basics", question: "What is the purpose of using a functional update form in useState?" },
    { id: 12, level: "Basics", question: "What happens if you update state with the same value as before?" },
    { id: 13, level: "Basics", question: "Can you store objects or arrays in useState? How do you update them correctly?" },
    { id: 14, level: "Basics", question: "What are common pitfalls when updating arrays or objects in useState?" },
    { id: 15, level: "Basics", question: "How does React know which useState call corresponds to which state variable?" },
    { id: 16, level: "Basics", question: "What happens if you call useState conditionally inside a component?" },
    { id: 17, level: "Basics", question: "What is the difference between props and state?" },
    { id: 18, level: "Basics", question: "How do you reset a state variable to its initial value?" },
    { id: 19, level: "Basics", question: "What happens if a component with useState is unmounted and then remounted?" },
    { id: 20, level: "Basics", question: "How would you debug issues where state updates are not triggering re-renders?" },
    { id: 21, level: "Intermediate", question: "What is lazy initialization in useState? (extended explanation)" },
    { id: 22, level: "Intermediate", question: "How can you preserve a value without causing unnecessary re-renders (useRef vs useState)?" },
    { id: 23, level: "Intermediate", question: "What are the Rules of Hooks?" },
    { id: 24, level: "Intermediate", question: "How can you minimize the number of re-renders when updating state?" },
    { id: 25, level: "Intermediate", question: "What happens to state when a component re-renders?" },
    { id: 26, level: "Intermediate", question: "Does updating state in useState immediately update the DOM?" },
    { id: 27, level: "Intermediate", question: "Can you store a function in useState?" },
    { id: 28, level: "Advanced", question: "What’s the difference between useState and useReducer? When would you use each?" },
    { id: 29, level: "Advanced", question: "What’s the difference between useState and useMemo/useCallback in terms of performance?" },
    { id: 30, level: "Advanced", question: "Is useState suitable for managing complex state? Why or why not?" },
    { id: 31, level: "Advanced", question: "How does React’s reconciliation algorithm interact with state updates?" },
    { id: 32, level: "Advanced", question: "What is the performance impact of using many useState calls in a single component?" },
];
const useEffectQuestions = [
    
]
const useMemoQuestions = [

]
const useCallbackQuestions = [
    
]
const htmlQuestions = [
    { id: 1, level: "Basics", question: "What is the difference between <div> and <span>?" },
    { id: 2, level: "Basics", question: "What is the difference between block elements and inline elements?" },
    { id: 3, level: "Basics", question: "What are semantic HTML tags? Give examples." },
    { id: 4, level: "Basics", question: "What is the purpose of <header>, <main>, and <footer>?" },
    { id: 5, level: "Basics", question: "What is the difference between <section> and <article>?" },
    { id: 6, level: "Basics", question: "What is the difference between <strong> and <b>?" },
    { id: 7, level: "Basics", question: "What is the difference between <em> and <i>?" },
    { id: 8, level: "Basics", question: "What is the DOCTYPE and why do we need it?" },
    { id: 9, level: "Basics", question: "What is the difference between HTML and XHTML?" },
    { id: 10, level: "Basics", question: "How can you improve accessibility in HTML pages?" },
    { id: 11, level: "Basics", question: "What is the purpose of the alt attribute on images?" },
    { id: 12, level: "Basics", question: "What is the difference between <link> and <a>?" },
    { id: 13, level: "Basics", question: "When should we use <button> vs <input type=\"button\">?" },
    { id: 14, level: "Basics", question: "What is the difference between relative and absolute URLs in HTML?" },
    { id: 15, level: "Basics", question: "What is the purpose of meta tags?" },
    { id: 16, level: "Intermediate", question: "What is the difference between <script>, <script async>, and <script defer>?" },
    { id: 17, level: "Intermediate", question: "What is the difference between inline, embedded, and external scripts in HTML?" },
    { id: 18, level: "Intermediate", question: "What are the uses of <canvas> and <svg>?" },
    { id: 19, level: "Intermediate", question: "How are video and audio handled in HTML5?" },
    { id: 20, level: "Intermediate", question: "What is the difference between localStorage, sessionStorage, and cookies?" },
]
const cssQuestions = [
    { id: 1, level: "Basics", question: "What is the difference between inline CSS, internal CSS, and external CSS?" },
    { id: 2, level: "Basics", question: "What is the difference between relative, absolute, fixed, and sticky positioning?" },
    { id: 3, level: "Basics", question: "What is the difference between Flexbox and Grid? When would you prefer each?" },
    { id: 4, level: "Basics", question: "What is the difference between em, rem, px, and % as units?" },
    { id: 5, level: "Basics", question: "What is z-index and how does it work?" },
    { id: 6, level: "Basics", question: "What is the difference between relative units and absolute units in CSS?" },
    { id: 7, level: "Basics", question: "What is the difference between pseudo-classes and pseudo-elements? Provide examples." },
    { id: 8, level: "Basics", question: "What is the difference between display: inline, inline-block, and block?" },
    { id: 9, level: "Basics", question: "What is the difference between visibility: hidden and display: none?" },
    { id: 10, level: "Basics", question: "What is the difference between absolute and relative paths in CSS imports?" },
    { id: 11, level: "Basics", question: "What is the difference between CSS specificity and the cascade?" },
    { id: 12, level: "Basics", question: "What are media queries and how are they used in responsive design?" },
    { id: 13, level: "Basics", question: "What is the difference between position: relative and position: absolute when used with a parent?" },
    { id: 14, level: "Basics", question: "What is the difference between transitions and animations in CSS?" },
    { id: 15, level: "Basics", question: "What is the difference between transform and translate in CSS?" },
    { id: 16, level: "Intermediate", question: "What is the difference between min-width, max-width, and width?" },
    { id: 17, level: "Intermediate", question: "What is the difference between fixed layout and fluid layout?" },
    { id: 18, level: "Intermediate", question: "What are the performance differences between inline styles and external stylesheets?" },
    { id: 19, level: "Intermediate", question: "What are CSS variables (custom properties) and what are their advantages?" },
    { id: 20, level: "Intermediate", question: "What is the difference between SASS and plain CSS? What are the advantages of preprocessors?" },
]
const jsQuestions = [
    { id: 1, level: "Basics", question: "What is the difference between var, let, and const?" },
    { id: 2, level: "Basics", question: "What is the difference between a function declaration and a function expression?" },
    { id: 3, level: "Basics", question: "What is an arrow function? What are its pros and cons?" },
    { id: 4, level: "Basics", question: "What is the difference between synchronous and asynchronous code?" },
    { id: 5, level: "Basics", question: "What is the difference between == and === in JavaScript?" },
    { id: 6, level: "Basics", question: "What is NaN and how do you check if a value is NaN?" },
    { id: 7, level: "Basics", question: "What is the difference between null and undefined?" },
    { id: 8, level: "Basics", question: "What is the difference between primitive types and reference types in JavaScript?" },
    { id: 9, level: "Basics", question: "What is the difference between the stack and the heap in memory management?" },
    { id: 10, level: "Basics", question: "What is the difference between a shallow copy and a deep copy?" },
    { id: 11, level: "Basics", question: "What is the difference between pass by value and pass by reference?" },
    { id: 12, level: "Basics", question: "What is the difference between Object.freeze and Object.seal?" },
    { id: 13, level: "Basics", question: "What is the difference between for...in and for...of?" },
    { id: 14, level: "Basics", question: "What is the difference between for loop, forEach, and map?" },
    { id: 15, level: "Basics", question: "What is the difference between slice and splice on arrays?" },
    { id: 16, level: "Basics", question: "What is the difference between map, filter, and reduce?" },
    { id: 17, level: "Basics", question: "What is the difference between find and findIndex?" },
    { id: 18, level: "Basics", question: "What is the difference between push and unshift?" },
    { id: 19, level: "Basics", question: "What is the difference between pop and shift?" },
    { id: 20, level: "Basics", question: "What is the difference between includes and indexOf?" },
    { id: 21, level: "Basics", question: "What is the difference between prototype and __proto__?" },
    { id: 22, level: "Basics", question: "What is prototypal inheritance?" },
    { id: 23, level: "Basics", question: "What is the difference between class syntax and a function constructor?" },
    { id: 24, level: "Basics", question: "What is the difference between static methods and instance methods in a class?" },
    { id: 25, level: "Basics", question: "What is the difference between private and public fields in a class?" },
    { id: 26, level: "Basics", question: "What is the difference between a getter and a setter in JavaScript?" },
    { id: 27, level: "Basics", question: "What is the difference between shallow inheritance and deep inheritance?" },
    { id: 28, level: "Basics", question: "What is the difference between mixins and inheritance?" },
    { id: 29, level: "Basics", question: "What is the difference between composition and inheritance?" },
    { id: 30, level: "Basics", question: "What is the difference between mutable and immutable objects?" },
    { id: 31, level: "Basics", question: "What is the difference between a pure function and an impure function?" },
    { id: 32, level: "Basics", question: "What is the functional programming paradigm?" },
    { id: 33, level: "Basics", question: "What is the difference between imperative and declarative programming?" },
    { id: 34, level: "Basics", question: "What is the difference between synchronous iteration and asynchronous iteration?" },
    { id: 35, level: "Basics", question: "What is a generator function and how do we use yield?" },
    { id: 36, level: "Basics", question: "What is the difference between a generator and an async function?" },
    { id: 37, level: "Basics", question: "What is the difference between an iterable and an iterator?" },
    { id: 38, level: "Basics", question: "What is a Symbol in JavaScript?" },
    { id: 39, level: "Basics", question: "What is the difference between using a Symbol and a string as object keys?" },
    { id: 40, level: "Basics", question: "What is the difference between Map and Object?" },
    { id: 41, level: "Basics", question: "What is the difference between Set and Array?" },
    { id: 42, level: "Intermediate", question: "What is the difference between call, apply, and bind?" },
    { id: 43, level: "Intermediate", question: "What is the difference between this in a regular function and in an arrow function?" },
    { id: 44, level: "Intermediate", question: "What is the difference between lexical scope and dynamic scope?" },
    { id: 45, level: "Intermediate", question: "What is the difference between function scope and block scope?" },
    { id: 46, level: "Intermediate", question: "What is hoisting and how does it work?" },
    { id: 47, level: "Intermediate", question: "What is the difference between the temporal dead zone and hoisting?" },
    { id: 48, level: "Intermediate", question: "What is an IIFE (Immediately Invoked Function Expression) and how is it different from a regular function?" },
    { id: 49, level: "Intermediate", question: "What is event bubbling?" },
    { id: 50, level: "Intermediate", question: "What is event capturing (trickling)?" },
    { id: 51, level: "Intermediate", question: "What is the difference between stopPropagation and stopImmediatePropagation?" },
    { id: 52, level: "Intermediate", question: "What is the difference between preventDefault and stopPropagation?" },
    { id: 53, level: "Intermediate", question: "What is debounce and how is it different from throttle?" },
    { id: 54, level: "Intermediate", question: "What is the difference between setTimeout and setInterval?" },
    { id: 55, level: "Intermediate", question: "What is the difference between a synchronous callback and an asynchronous callback?" },
    { id: 56, level: "Intermediate", question: "What is a Promise in JavaScript?" },
    { id: 57, level: "Intermediate", question: "What is the difference between promise chaining and async/await?" },
    { id: 58, level: "Intermediate", question: "What is the difference between requestAnimationFrame and setTimeout?" },
    { id: 59, level: "Intermediate", question: "What is the difference between WeakMap and Map?" },
    { id: 60, level: "Intermediate", question: "What is the difference between WeakSet and Set?" },
    { id: 61, level: "Intermediate", question: "What is the difference between JSON.parse and eval?" },
    { id: 62, level: "Intermediate", question: "What is the difference between structured cloning and JSON serialization?" },
    { id: 63, level: "Intermediate", question: "What is the difference between deep cloning with structuredClone and JSON.parse(JSON.stringify(...))?" },
    { id: 64, level: "Intermediate", question: "What is the difference between module.exports and exports in Node.js?" },
    { id: 65, level: "Intermediate", question: "What is the difference between CommonJS and ES Modules?" },
    { id: 66, level: "Intermediate", question: "What is the difference between default import and named import?" },
    { id: 67, level: "Intermediate", question: "What is the difference between dynamic import and static import?" },
    { id: 68, level: "Intermediate", question: "What is tree shaking?" },
    { id: 69, level: "Intermediate", question: "What is bundling in JavaScript?" },
    { id: 70, level: "Intermediate", question: "What is transpiling?" },
    { id: 71, level: "Intermediate", question: "What is the difference between a polyfill and a shim?" },
    { id: 72, level: "Intermediate", question: "What is a Service Worker?" },
    { id: 73, level: "Intermediate", question: "What is the difference between localStorage, sessionStorage, and IndexedDB?" },
    { id: 74, level: "Intermediate", question: "What is the difference between synchronous APIs and asynchronous APIs in the browser?" },
    { id: 75, level: "Advanced", question: "What is the difference between the microtask queue and the macrotask queue?" },
    { id: 76, level: "Advanced", question: "What is the difference between try...catch and error boundaries?" },
    { id: 77, level: "Advanced", question: "What is the difference between throw new Error and console.error?" },
    { id: 78, level: "Advanced", question: "What is the Event Loop and how does it work?" },
    { id: 79, level: "Advanced", question: "What is the difference between the Call Stack and the Callback Queue?" },
]
const reactQuestions = [
    { id: 1, level: "Basics", question: "What is React and why do we use it?" },
    { id: 2, level: "Basics", question: "What is the difference between React and Vanilla JavaScript?" },
    { id: 3, level: "Basics", question: "What is the difference between React, Angular, and Vue?" },
    { id: 4, level: "Basics", question: "What is a Component in React?" },
    { id: 5, level: "Basics", question: "What is the difference between a functional component and a class component?" },
    { id: 6, level: "Basics", question: "What is the difference between JSX and HTML?" },
    { id: 7, level: "Basics", question: "What is the Virtual DOM?" },
    { id: 8, level: "Basics", question: "What is JSX?" },
    { id: 9, level: "Basics", question: "What is the difference between props and state?" },
    { id: 10, level: "Basics", question: "What is the difference between a controlled component and an uncontrolled component?" },
    { id: 13, level: "Basics", question: "What is the difference between one-way data flow and two-way data binding?" },
    { id: 14, level: "Basics", question: "What are default props?" },
    { id: 15, level: "Basics", question: "What are prop types and why do we use them?" },
    { id: 16, level: "Basics", question: "What is the difference between the children prop and custom props?" },
    { id: 17, level: "Basics", question: "What is the difference between conditional rendering with && and the ternary operator?" },
    { id: 18, level: "Basics", question: "What is the difference between inline styling and CSS modules in React?" },
    { id: 19, level: "Basics", question: "What is the difference between React.Fragment and a div?" },
    { id: 20, level: "Basics", question: "What is the difference between React.Fragment and the <> shorthand?" },
    { id: 21, level: "Basics", question: "What are keys in React and why do we need them?" },
    { id: 22, level: "Basics", question: "What is the difference between useState and setState (in class components)?" },
    { id: 23, level: "Basics", question: "What is the difference between local state and global state?" },
    { id: 24, level: "Basics", question: "What is the difference between client-side routing and server-side routing?" },
    { id: 25, level: "Basics", question: "What is the difference between HashRouter and BrowserRouter?" },
    { id: 26, level: "Basics", question: "What is the difference between dynamic routes and static routes?" },
    { id: 27, level: "Intermediate", question: "How does reconciliation work in React?" },
    { id: 28, level: "Intermediate", question: "What is the difference between ReactDOM.render and createRoot (React 18)?" },
    { id: 29, level: "Intermediate", question: "What is the difference between passing props and lifting state up?" },
    { id: 30, level: "Intermediate", question: "What are the reconciliation rules related to keys?" },
    { id: 31, level: "Intermediate", question: "What is the difference between initial state and derived state?" },
    { id: 32, level: "Intermediate", question: "What is the difference between useEffect and componentDidMount?" },
    { id: 33, level: "Intermediate", question: "What is the difference between useEffect and useLayoutEffect?" },
    { id: 34, level: "Intermediate", question: "What is the difference between a cleanup function in useEffect and not having one?" },
    { id: 35, level: "Intermediate", question: "What is the difference between an empty dependency array [] and [value] in useEffect?" },
    { id: 36, level: "Intermediate", question: "What is the difference between a re-render and a re-mount in React?" },
    { id: 37, level: "Intermediate", question: "What is the difference between a single source of truth and multiple states?" },
    { id: 38, level: "Intermediate", question: "What is the difference between lifting state up and prop drilling?" },
    { id: 39, level: "Intermediate", question: "What is the difference between prop drilling and the Context API?" },
    { id: 40, level: "Intermediate", question: "What is the difference between the Context API and Redux?" },
    { id: 41, level: "Intermediate", question: "What is the difference between controlled forms and uncontrolled forms in React?" },
    { id: 42, level: "Intermediate", question: "What is the difference between one-way data binding and two-way binding in React forms?" },
    { id: 43, level: "Intermediate", question: "What is the difference between useRef and createRef?" },
    { id: 44, level: "Intermediate", question: "What is the difference between forwardRef and useRef?" },
    { id: 45, level: "Intermediate", question: "What is memoization in React (React.memo, useMemo, useCallback)?" },
    { id: 46, level: "Intermediate", question: "What is the difference between React.StrictMode and normal mode?" },
    { id: 47, level: "Intermediate", question: "What is the difference between server components and client components (React 18/Next.js 13+)?" },
    { id: 48, level: "Intermediate", question: "What is the difference between SSR, CSR, and SSG?" },
    { id: 49, level: "Intermediate", question: "What is the difference between hydration and rendering?" },
    { id: 50, level: "Intermediate", question: "What is the difference between lazy loading and code splitting?" },
    { id: 51, level: "Intermediate", question: "What is the difference between React.lazy and dynamic import?" },
    { id: 52, level: "Intermediate", question: "What is the difference between Suspense and Error Boundaries?" },
    { id: 53, level: "Intermediate", question: "What is the difference between useMemo and useCallback?" },
    { id: 54, level: "Intermediate", question: "What is the difference between memoization and caching?" },
    { id: 55, level: "Intermediate", question: "What is the difference between React.memo and PureComponent?" },
    { id: 56, level: "Intermediate", question: "What is the difference between reconciliation in React and traditional DOM diffing?" },
    { id: 57, level: "Intermediate", question: "What is the difference between synthetic events in React and native DOM events?" },
    { id: 58, level: "Intermediate", question: "What is the difference between batching updates and unbatched updates?" },
    { id: 59, level: "Intermediate", question: "What is the Transition API in React 18?" },
    { id: 60, level: "Intermediate", question: "What is the difference between useDeferredValue and useTransition?" },
    { id: 61, level: "Intermediate", question: "What is the difference between server-sent events and WebSockets in React apps?" },
    { id: 62, level: "Intermediate", question: "What is the difference between useNavigate and useHistory (React Router v6 vs v5)?" },
    { id: 63, level: "Advanced", question: "What is the difference between concurrent rendering and legacy rendering?" },
  
]   
const nextQuestions = [
    { id: 1, level: "Basics", question: "What is Next.js and how is it different from plain React?" },
    { id: 2, level: "Basics", question: "What is the difference between the App Router and Pages Router in Next.js?" },
    { id: 3, level: "Basics", question: "What is the difference between server-side rendering (SSR) and static site generation (SSG) in Next.js?" },
    { id: 4, level: "Basics", question: "What is the difference between getServerSideProps and getStaticProps?" },
    { id: 5, level: "Basics", question: "What is the difference between getStaticPaths and getServerSideProps?" },
    { id: 6, level: "Basics", question: "What is the difference between a client component and a server component in Next.js 13+?" },
    { id: 10, level: "Basics", question: "What is the difference between Next.js's Image component and a regular <img>?" },
    { id: 11, level: "Basics", question: "What is the difference between Next.js's Link component and a regular <a>?" },
    { id: 20, level: "Basics", question: "What is the difference between next.config.js and .env.local in Next.js?" },
    { id: 7, level: "Intermediate", question: "What is the difference between useRouter in the App Router and useRouter in the Pages Router?" },
    { id: 8, level: "Intermediate", question: "What is the difference between layout.js and template.js in Next.js?" },
    { id: 9, level: "Intermediate", question: "What is the difference between middleware.js and API routes in Next.js?" },
    { id: 12, level: "Intermediate", question: "What is the difference between next/head and document.js?" },
    { id: 13, level: "Intermediate", question: "What is the difference between dynamic routes and catch-all routes in Next.js?" },
    { id: 14, level: "Intermediate", question: "What is the difference between parallel routes and intercepting routes in Next.js 13?" },
    { id: 15, level: "Intermediate", question: "What is the difference between static rendering and dynamic rendering in Next.js?" },
    { id: 16, level: "Intermediate", question: "What is the difference between Next.js API routes and external APIs?" },
    { id: 17, level: "Intermediate", question: "What is the difference between edge functions and serverless functions in Next.js?" },
    { id: 18, level: "Intermediate", question: "What is the difference between revalidate in SSG and SSR?" },
    { id: 19, level: "Intermediate", question: "What is the difference between deploying on Vercel and other hosting providers with Next.js?" },
]
const typescriptQuestions = [
    { id: 1, level: "Basics", question: "What is the difference between TypeScript and JavaScript?" },
    { id: 2, level: "Basics", question: "What is the difference between type and interface in TypeScript?" },
    { id: 3, level: "Basics", question: "What is the difference between optional properties and required properties?" },
    { id: 4, level: "Basics", question: "What is the difference between union types and intersection types?" },
    { id: 5, level: "Basics", question: "What is the difference between any and unknown?" },
    { id: 7, level: "Basics", question: "What is the difference between type inference and type annotation?" },
    { id: 12, level: "Basics", question: "What is the difference between enums and literal types?" },
    { id: 14, level: "Basics", question: "What is the difference between readonly and const?" },
    { id: 20, level: "Basics", question: "What is the difference between tsconfig.json and jsconfig.json?" },
    { id: 6, level: "Intermediate", question: "What is the difference between never and void?" },
    { id: 8, level: "Intermediate", question: "What is the difference between structural typing and nominal typing?" },
    { id: 9, level: "Intermediate", question: "What is the difference between generic functions and normal functions?" },
    { id: 10, level: "Intermediate", question: "What is the difference between keyof and typeof?" },
    { id: 11, level: "Intermediate", question: "What is the difference between type assertion and type casting?" },
    { id: 15, level: "Intermediate", question: "What is the difference between Partial and Required utility types?" },
    { id: 16, level: "Intermediate", question: "What is the difference between Pick and Omit utility types?" },
    { id: 17, level: "Intermediate", question: "What is the difference between Exclude and Extract utility types?" },
    { id: 18, level: "Intermediate", question: "What is the difference between Record and Map in TypeScript?" },
    { id: 19, level: "Advanced", question: "What is the difference between declaration files and ambient types?" },
]
const PerformanceOptimizationQuestions = [
    { id: 1, level: "Basics", question: "What is the difference between minification and compression?" },
    { id: 2, level: "Basics", question: "What is the difference between lazy loading and code splitting?" },
    { id: 3, level: "Basics", question: "What is the difference between preloading and prefetching?" },
    { id: 4, level: "Basics", question: "What is the difference between CDN caching and browser caching?" },
    { id: 5, level: "Basics", question: "What is the difference between image optimization and responsive images?" },
    { id: 6, level: "Basics", question: "What is the difference between inline critical CSS and external CSS?" },
    { id: 7, level: "Basics", question: "What is the difference between throttling and debouncing for performance?" },
    { id: 8, level: "Basics", question: "What is the difference between memoization and caching?" },
    { id: 9, level: "Basics", question: "What is the difference between gzip and Brotli?" },
    { id: 10, level: "Basics", question: "What is the difference between static imports and dynamic imports for performance?" },
    { id: 11, level: "Intermediate", question: "What is the difference between HTTP/1.1, HTTP/2, and HTTP/3 in terms of speed?" },
    { id: 12, level: "Intermediate", question: "What is the difference between server-side rendering and client-side rendering from a performance perspective?" },
    { id: 13, level: "Intermediate", question: "What is the difference between a long task and a short task in the browser?" },
    { id: 14, level: "Intermediate", question: "What is the difference between repaint and reflow in the browser?" },
    { id: 15, level: "Intermediate", question: "What is the difference between hydration and streaming SSR?" },
    { id: 16, level: "Intermediate", question: "What is the difference between Lighthouse and WebPageTest?" },
    { id: 17, level: "Intermediate", question: "What is the difference between a performance budget and a bundle analyzer?" },
    { id: 18, level: "Intermediate", question: "What is the difference between tree shaking and dead code elimination?" },
    { id: 19, level: "Intermediate", question: "What is the difference between client-side caching and server-side caching?" },
    { id: 20, level: "Intermediate", question: "What is the difference between Service Worker caching and traditional caching?" },
]
const WebSecurityQuestions = [
    { id: 1, level: "Basics", question: "What is the difference between HTTP and HTTPS?" },
    { id: 2, level: "Basics", question: "What is the difference between SSL and TLS?" },
    { id: 3, level: "Basics", question: "What is the difference between symmetric encryption and asymmetric encryption?" },
    { id: 4, level: "Basics", question: "What is the difference between hashing and encryption?" },
    { id: 5, level: "Basics", question: "What is the difference between salting and hashing?" },
    { id: 6, level: "Basics", question: "What is the difference between XSS (Cross-Site Scripting) and CSRF (Cross-Site Request Forgery)?" },
    { id: 7, level: "Basics", question: "What is the difference between stored XSS and reflected XSS?" },
    { id: 8, level: "Basics", question: "What is the difference between authorization and authentication?" },
    { id: 9, level: "Basics", question: "What is the difference between HttpOnly and Secure cookies?" },
    { id: 10, level: "Basics", question: "What is the difference between a brute-force attack and a dictionary attack?" },
    { id: 11, level: "Intermediate", question: "What is the difference between Content Security Policy (CSP) and CORS?" },
    { id: 12, level: "Intermediate", question: "What is the difference between the same-origin policy and cross-origin requests?" },
    { id: 13, level: "Intermediate", question: "What is the difference between a preflight request and a simple request in CORS?" },
    { id: 14, level: "Intermediate", question: "What is the difference between JWT and session-based authentication?" },
    { id: 15, level: "Intermediate", question: "What is the difference between an access token and a refresh token?" },
    { id: 16, level: "Intermediate", question: "What is the difference between OAuth2 and OpenID Connect?" },
    { id: 17, level: "Intermediate", question: "What is the difference between SQL Injection and NoSQL Injection?" },
    { id: 18, level: "Intermediate", question: "What is the difference between penetration testing and vulnerability scanning?" },
    { id: 19, level: "Intermediate", question: "What is the difference between rate limiting and throttling from a security perspective?" },
    { id: 20, level: "Intermediate", question: "What is the difference between security headers such as HSTS, X-Frame-Options, and X-Content-Type-Options?" },
]
const GeneralFrontendConceptsQuestions = [
    { id: 1, level: "Basics", question: "What is the difference between progressive enhancement and graceful degradation?" },
    { id: 2, level: "Basics", question: "What is the difference between SPA (Single Page Application) and MPA (Multi-Page Application)?" },
    { id: 3, level: "Basics", question: "What is the difference between a static website and a dynamic website?" },
    { id: 4, level: "Basics", question: "What is the difference between client-side rendering and server-side rendering?" },
    { id: 5, level: "Basics", question: "What is the difference between responsive design and adaptive design?" },
    { id: 6, level: "Basics", question: "What is the difference between mobile-first design and desktop-first design?" },
    { id: 7, level: "Basics", question: "What is the difference between UX (User Experience) and UI (User Interface)?" },
    { id: 8, level: "Basics", question: "What is the difference between accessibility (a11y) and usability?" },
    { id: 9, level: "Basics", question: "What is the difference between a wireframe and a prototype?" },
    { id: 10, level: "Basics", question: "What is the difference between high-fidelity and low-fidelity prototypes?" },
    { id: 11, level: "Basics", question: "What is the difference between a design system and a style guide?" },
    { id: 12, level: "Basics", question: "What is the difference between dark mode and light mode from a design perspective?" },
    { id: 13, level: "Intermediate", question: "What is the difference between the critical rendering path and the render tree?" },
    { id: 14, level: "Intermediate", question: "What is the difference between the DOM and the Virtual DOM?" },
    { id: 15, level: "Intermediate", question: "What is the difference between hydration and rehydration?" },
    { id: 16, level: "Intermediate", question: "What is the difference between a stateful component and a stateless component?" },
    { id: 17, level: "Intermediate", question: "What is the difference between monolith architecture and microservices architecture?" },
    { id: 18, level: "Intermediate", question: "What is the difference between a headless CMS and a traditional CMS?" },
    { id: 19, level: "Intermediate", question: "What is the difference between the JAMstack and the LAMP stack?" },
    { id: 20, level: "Intermediate", question: "What is the difference between API-first design and backend-driven UI?" },
]
const TestingQuestions = [
    { id: 1, level: "Basics", question: "What is Unit Testing in JavaScript?" },
    { id: 2, level: "Basics", question: "What are some popular JavaScript testing frameworks?" },
    { id: 3, level: "Basics", question: "What is Jest?" },
    { id: 4, level: "Basics", question: "What is End-to-End (E2E) Testing?" },
    { id: 5, level: "Basics", question: "What is a Mock in testing?" },
    { id: 6, level: "Basics", question: "What is Code Coverage?" },
    { id: 7, level: "Intermediate", question: "What is the difference between Unit Testing and Integration Testing?" },
    { id: 8, level: "Intermediate", question: "What is Test-Driven Development (TDD)?" },
    { id: 9, level: "Intermediate", question: "What is Continuous Integration (CI)?" },
]
const BuildToolsQuestions = [
    { id: 1, level: "Basics", question: "What is a Build Tool?" },
    { id: 2, level: "Basics", question: "What are popular JavaScript build tools?" },
    { id: 3, level: "Basics", question: "What is Webpack?" },
    { id: 4, level: "Basics", question: "What is Babel?" },
    { id: 5, level: "Intermediate", question: "What is the difference between Webpack and Babel?" },
]
const LintingFormattingQuestions = [
    { id: 1, level: "Basics", question: "What is ESLint?" },
    { id: 2, level: "Basics", question: "What is Prettier?" },
    { id: 3, level: "Intermediate", question: "What is the difference between ESLint and Prettier?" },
]
const PackageManagementQuestions = [
    { id: 1, level: "Basics", question: "What is a Package Manager?" },
    { id: 2, level: "Basics", question: "What is the difference between npm and yarn?" },
]
const MonorepoQuestions = [
    { id: 1, level: "Basics", question: "What is a Monorepo?" },
    { id: 2, level: "Intermediate", question: "What are common monorepo tools (Nx, Lerna, Turborepo)?" },
]


